### PR TITLE
Add cluster-sync to test.sh.

### PR DESCRIPTION
**Pull request by leongold**

### CODE REVIEW

**Comment by SchSeba** [comment]
ci test please

**Comment by leongold** [comment]
@phoracek review pls

**Comment by phoracek** [comment]
Please add some more text to the commit message, I have no idea why do you do that.

Plus the title:
s/Readd/Read/

**Comment by leongold** [comment]
> Re-add? Don't mind me...

It's actually just add; it was never in test.sh apparently.

**Comment by phoracek** [comment]
Is this PR alone good for something? Don't you want to add those two lines together with an actual test?

**Comment by leongold** [comment]
> Is this PR alone good for something? Don't you want to add those two lines together with an actual test?

This is good by its own. There were several PR's merged recently, each one adding functionality to CI. This one deploy ovs-cni, and following code in test.sh checks the pods manage to run successfully.

**Comment by phoracek** [comment]
I see, LGTM

**Pull request merged**
