### PR TITLE
Add IPAM support

### PR DESCRIPTION
**Pull request by pperiyasamy**
This change would integrate an ipam module through network attachment definition for the ovs-cni.

Let me add writing unit tests in the subsequent commit once this commit is reviewed.

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by pperiyasamy** [comment]
@phoracek Looks this PR had another commit "Merge pull request #2 from kubevirt/master" which is incorrect.  Can we close this PR and create another one properly ? sorry for that.

**Comment by phoracek** [comment]
Sure, whatever is the most convenient way for you. Either rebase this or push a new PR.

**Comment by pperiyasamy** [comment]
As per the [comment](https://github.com/kubevirt/ovs-cni/pull/101#issuecomment-580224694), it's an invalid PR, closing it.

**Pull request closed without merging**
