### PR TITLE
use go 1.10

### PR DESCRIPTION
**Pull request by phoracek**
Let's upgrade to Go 1.10. That allows us to drop nsenter workarounds.

### CODE REVIEW

**Comment by SchSeba** [comment]
@phoracek Can you please fix the CI also

https://jenkins.ovirt.org/job/kubevirt_ovs-cni_standard-check-pr/146//artifact/check-patch.k8s-multus-1.11.1-release.el7.x86_64/mock_logs/script/stdout_stderr.log

The problem is we try to build with a lower version of go I think.

**Comment by phoracek** [comment]
@SchSeba could you review please? It passed on STD-CI Kubernetes.

**Comment by SchSeba** [comment]
@phoracek Can you please rebase and let the tests run?

**Comment by phoracek** [comment]
@SchSeba done, passed

**Comment by SchSeba** [comment]
The build looks good. new image 
`quay.io/kubevirt/ovs-cni-plugin@sha256:a1e994f516fc3325f430815b9bf86ed1b3cb7654b7b315c1d758e0035b3f1e58`

**Pull request merged**
