### PR TITLE
add ipam support

### PR DESCRIPTION
**Pull request by pperiyasamy**
This adds ipam facility for the ovs-cni through network attachment definition.

Signed-off-by: Periyasamy Palanisamy <periyasamy.palanisamy@est.tech>

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by phoracek** [comment]
Thanks a lot for this interesting contribution. Once it is ready for review (tests are in place), please let me know :)

**Comment by pperiyasamy** [comment]
@phoracek Now ipam unit test changes are done, but ci is failing with below error.

```
Unexpected error:
          <*errors.errorString | 0xc000474230>: {
              s: "failed to set up IPAM plugin type \"host-local\": failed to find plugin \"host-local\" in path [/gimme/.gimme/versions/go1.12.linux.amd64/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin]",
          }
          failed to set up IPAM plugin type "host-local": failed to find plugin "host-local" in path [/gimme/.gimme/versions/go1.12.linux.amd64/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin]
      occurred
      /root/go/src/github.com/kubevirt/ovs-cni/pkg/plugin/plugin_test.go:111
```

shouldn't we have host-local binary into the `PATH` ?

**Comment by phoracek** [comment]
There are no CNI plugins installed in the docker container we use for testing. If you run it on your setup without containerization, you need the IPAM CNI binary in your PATH.

We should download the  `host-local` binary to the test container and add a note to documentation that it is required to have it in local PATH if not running containerized (plus link to the binary).

Docker image should be updated here https://github.com/kubevirt/ovs-cni/blob/master/hack/docker-builder/Dockerfile. You can use `ADD` from https://github.com/containernetworking/plugins/releases/download/v0.8.5/cni-plugins-linux-amd64-v0.8.5.tgz and then extract needed plugins into PATH.

Documentation should be updated here https://github.com/kubevirt/ovs-cni/blob/master/docs/cni-plugin.md#go-tests.

**Comment by pperiyasamy** [comment]
@phoracek The required changes are made to make ipam test to pass. Can you have a look now ?

**Comment by phoracek** [comment]
/lgtm

Thanks, great contribution :)

**Pull request merged**
