### PR TITLE
Fix Link Error in deployment-on-arbitrary-cluster.md

### PR DESCRIPTION
**Pull request by vanou**
This commit fixes wrong URL in docs/deployment-on-arbitrary-cluster.md

### CODE REVIEW

**Comment by phoracek** [comment]
Looks good, thanks @vanou 

We require commits to be signed. Would you please amend the commit with `git commit -s -amend` and force push it again?

**Comment by vanou** [comment]
Thanks @phoracek !
I signed my commit & amended commit.

**Comment by phoracek** [comment]
Thanks a lot :rocket: 

/lgtm
/approve

**Pull request merged**
